spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: Student
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/**
        - id: Department
          uri: http://localhost:8081
          predicates:
            - Path=/api/v2/**
        - id: gateway
          uri: http://localhost:8082
          predicates:
              - Path=/**